FROM python:3.8

WORKDIR /usr/src/backend

COPY ./ ./

# cron configuration 
RUN apt update && apt install -y cron
RUN crontab crontab-backend

# supervisor configuration 
RUN apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor
COPY sup-docker.conf /etc/supervisor/conf.d/sup-docker.conf

# RUN apt update && apt install -y cron
# COPY crontab-backend /etc/cron.d/example-crontab
# RUN chmod 0644 /etc/cron.d/example-crontab
# RUN crontab /etc/cron.d/example-crontab

RUN pip install wheel

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install gunicorn

CMD ["./docker-entry.sh"]
